server:
  port: 8762

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/